site_name: Sudobox Docs
site_url: https://docs.sudobox.io/
site_author: sudobox
site_description: Some Sudobox description

repo_name: sb-documentation
repo_url: https://github.com/sudobox-io/sb-documentation

edit_uri: edit/master/docs/

theme:
  name: material
  custom_dir: overrides
  features:
    - navigation.instant
    - navigation.tracking
    - navigation.sections
    - navigation.expand
    - navigation.tabs
    - navigation.tabs.sticky
    - search.suggest
    - search.highlight
    - search.share
  logo: images/sb_logo.png
  favicon: images/sb_logo.png
  palette:
    - scheme: slate 

extra:
  version:
    provider: mike
  generator: false
  social:
  - icon: fontawesome/solid/heart
    link: '/'
    name: Donate
  - icon: fontawesome/brands/discord
    link: 'https://discord.gg/sudobox'
    name: Discord
  - icon: fontawesome/brands/github
    link: 'https://github.com/sudobox-io/sb-install'
    name: GitHub

plugins:
  - search:
      lang: en

markdown_extensions:
  - pymdownx.highlight:
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true 

extra_css:
  - stylesheets/extra.css

nav:
  - Home: index.md
  - Get Started:
    - Installation:
      - Installer: "get-started/installation/installer.md"
    - Prerequisites:
      - Server: "get-started/prerequisites/server.md"
      - CloudFlare: "get-started/prerequisites/cloudflare.md"
      - Domain: "get-started/prerequisites/domain.md"
  - Apps:
      - Core: 
        - SB-Mount: "apps/core/sb-mount.md"             
        - SB-Uploader: "apps/core/sb-uploader.md"
      - Supported: 
        - Plex: "apps/supported/plex.md"
  - Troubleshooting: "troubleshooting/troubleshooting.md"
  - FAQ: index.md


